export interface PitTableRow {
  code?: string;
  desc?: string;
  peso?: number | string;
  max?: number | string;
  unidade?: string;
  q?: string;
  t?: string;
  readonly?: boolean;
  isSubtotal?: boolean;
}

export const PIT_SHEET_DATA: { title: string; rows: PitTableRow[] }[] = [
  {
    title: '1 AULAS EM FIC, TÉCNICO, ESPECIALIZAÇÃO...',
    rows: [
      {
        code: '1.1',
        desc: 'Cursos Técnico e/ou Licenciaturas',
        peso: 1,
        max: 20,
        unidade: 'Créditos',
        q: 'q1',
        t: 't1',
      },
      {
        code: '1.2',
        desc: 'Cursos de Especialização, Graduação e Pós-Graduação',
        peso: 1,
        max: 20,
        unidade: 'Créditos',
        q: 'q2',
        t: 't2',
      },
      {
        code: '1.3',
        desc: 'Cursos FIC (Observar a regulamentação)',
        peso: 0.05,
        max: 400,
        unidade: 'Horas',
        q: 'q3',
        t: 't3',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '2 ATIVIDADES DE MANUTENÇÃO AO ENSINO (até 18 horas)',
    rows: [
      {
        code: '2.1',
        desc: 'Preparação + Planejamento',
        peso: 0.8,
        max: 14,
        unidade: 'Horas',
        q: 'q4',
        t: 't4',
      },
      {
        code: '2.2',
        desc: 'Atendimento a Estudantes',
        peso: 0.2,
        max: 4,
        unidade: 'Horas',
        q: 'q5',
        t: 't5',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '3 ATIVIDADES DE APOIO AO ENSINO (2 horas)',
    rows: [
      {
        code: '3.1',
        desc: 'Participação nos encontros técnico-pedagógicos',
        peso: 1,
        max: 1,
        unidade: '-',
        q: 'q6',
        t: 't6',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '4 ATIVIDADES DE ORIENTAÇÃO (até 10 horas)',
    rows: [
      {
        code: '4.1',
        desc: 'Orientação de TCC graduação',
        peso: 1,
        max: 6,
        unidade: 'Estudantes',
        q: 'q7',
        t: 't7',
      },
      {
        code: '4.2',
        desc: 'Orientação de Estágio (Supervisor-Orientador)',
        peso: 1,
        max: 4,
        unidade: 'Estudantes',
        q: 'q8',
        t: 't8',
      },
      {
        code: '4.3',
        desc: 'Orientação de Estágio (Regulamentação diferenciada)',
        peso: 2,
        max: 4,
        unidade: 'Estudantes',
        q: 'q9',
        t: 't9',
      },
      {
        code: '4.4',
        desc: 'Monitoria',
        peso: 2,
        max: 1,
        unidade: 'Estudantes',
        q: 'q10',
        t: 't10',
      },
      {
        code: '4.5',
        desc: 'Programa Institucional (PIBID) / Programas de Êxito',
        peso: 10,
        max: 1,
        unidade: 'Programa',
        q: 'q11',
        t: 't11',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '5 ATIVIDADES DE ENSINO EXTRACURRICULAR (até 10 horas)',
    rows: [
      {
        code: '5.1',
        desc: 'Responsável por Laboratório',
        peso: 8,
        max: 1,
        unidade: 'Laboratórios',
        q: 'q12',
        t: 't12',
      },
      {
        code: '5.2',
        desc: 'Projetos ou atividades complementares extras',
        peso: 1,
        max: 2,
        unidade: 'Projetos',
        q: 'q13',
        t: 't13',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '6 ATIVIDADES DE PESQUISA APLICADA (até 18 horas)',
    rows: [
      {
        code: '6.1',
        desc: 'Coord. projeto pesquisa fomento IFCE ou sem recurs.',
        peso: 4.0,
        max: 3.0,
        unidade: 'Projetos',
        q: 'q14',
        t: 't14',
      },
      {
        code: '6.2',
        desc: 'Coord. projeto pesquisa com captação externa',
        peso: 6.0,
        max: 2.0,
        unidade: 'Projetos',
        q: 'q15',
        t: 't15',
      },
      {
        code: '6.3',
        desc: 'Participação em equipe de projeto pesquisa',
        peso: 3.0,
        max: 2.0,
        unidade: 'Projetos',
        q: 'q16',
        t: 't16',
      },
      {
        code: '6.4',
        desc: 'Orient. especialização, Co-orientação Mestrado/Doutorado',
        peso: 2.0,
        max: 4.0,
        unidade: 'Estudantes',
        q: 'q17',
        t: 't17',
      },
      {
        code: '6.5',
        desc: 'Bolsista produtividade PQ, DT do CNPq',
        peso: 16.0,
        max: 1.0,
        unidade: 'Bolsas',
        q: 'q18',
        t: 't18',
      },
      {
        code: '6.6',
        desc: 'Part. stricto sensu COLABORADOR',
        peso: 8.0,
        max: 1.0,
        unidade: 'Programas',
        q: 'q19',
        t: 't19',
      },
      {
        code: '6.7',
        desc: 'Part. stricto sensu PERMANENTE',
        peso: 16.0,
        max: 1.0,
        unidade: 'Programas',
        q: 'q20',
        t: 't20',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '7 ATIVIDADES DE EXTENSÃO (até 18 horas)',
    rows: [
      {
        code: '7.1',
        desc: 'Coord. projeto extensão fomento IFCE ou sem res.',
        peso: 4.0,
        max: 3.0,
        unidade: 'Projetos',
        q: 'q21',
        t: 't21',
      },
      {
        code: '7.2',
        desc: 'Coord. projeto extensão captação de recursos',
        peso: 6.0,
        max: 2.0,
        unidade: 'Projetos',
        q: 'q22',
        t: 't22',
      },
      {
        code: '7.3',
        desc: 'Participação em equipe de extensão, exceto FIC',
        peso: 3.0,
        max: 2.0,
        unidade: 'Projetos',
        q: 'q23',
        t: 't23',
      },
      {
        code: '7.4',
        desc: 'Coordenação incubadoras de empresas',
        peso: 16.0,
        max: 1.0,
        unidade: 'Coordenações',
        q: 'q24',
        t: 't24',
      },
      {
        code: '7.5',
        desc: 'Coordenação dos NAPNEs e NEABIs',
        peso: 5.0,
        max: 1.0,
        unidade: 'Coordenações',
        q: 'q25',
        t: 't25',
      },
      {
        code: '7.6',
        desc: 'Participação em NAPNEs e NEABIs',
        peso: 3.0,
        max: 1.0,
        unidade: 'Participações',
        q: 'q26',
        t: 't26',
      },
      {
        code: '7.7',
        desc: 'Cursos FIC (Horas por curso)',
        peso: 0.05,
        max: 240.0,
        unidade: 'Duração',
        q: 'q27',
        t: 't27',
      },
      {
        code: '7.8',
        desc: 'Preparação + Planejamento cursos FIC',
        peso: 0.05,
        max: 120.0,
        unidade: 'Duração',
        q: 'q28',
        t: 't28',
      },
      {
        code: '7.9',
        desc: 'Planejamento e organ. de eventos de extensão',
        peso: 1.0,
        max: 2.0,
        unidade: 'Eventos',
        q: 'q29',
        t: 't29',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '8 ATIVIDADES DE GESTÃO INSTITUCIONAL E ACADÊMICA (até 18 horas)',
    rows: [
      {
        code: '8.1',
        desc: 'Coordenador de Curso',
        peso: 18.0,
        max: 1,
        unidade: 'Curso',
        q: 'q30',
        t: 't30',
      },
      {
        code: '8.2',
        desc: 'Coordenador de Setor',
        peso: 18.0,
        max: 1,
        unidade: 'Setor',
        q: 'q31',
        t: 't31',
      },
      {
        code: '8.3',
        desc: 'Chefe de Departamento',
        peso: 18.0,
        max: 1,
        unidade: 'Departament.',
        q: 'q32',
        t: 't32',
      },
      {
        code: '8.4',
        desc: 'Diretores de Área/Setor',
        peso: 18.0,
        max: 1,
        unidade: 'Área',
        q: 'q33',
        t: 't33',
      },
      {
        code: '8.5',
        desc: 'Assessor da Reitoria',
        peso: 18.0,
        max: 1,
        unidade: 'Assessoria',
        q: 'q34',
        t: 't34',
      },
      {
        code: '8.6',
        desc: 'Coordenador Implantação de Campus',
        peso: 18.0,
        max: 1,
        unidade: 'Coordenação',
        q: 'q35',
        t: 't35',
      },
      {
        code: '8.7',
        desc: 'Assistente Pró-Reitoria / Gabinete',
        peso: 18.0,
        max: 1,
        unidade: 'Assessoria',
        q: 'q36',
        t: 't36',
      },
      {
        code: '8.8',
        desc: 'Coord. prog. institucional (Ensino/Pesq./Ext)',
        peso: 18.0,
        max: 1,
        unidade: 'Programa',
        q: 'q37',
        t: 't37',
      },
      { isSubtotal: true },
    ],
  },
  {
    title: '9 ATIVIDADES EM COMISSÕES OU DE FISCALIZAÇÃO (até 18 horas)',
    rows: [
      {
        code: '9.1',
        desc: 'Conselhos, comissões permanecentes.',
        peso: 3.0,
        max: 1,
        unidade: '-',
        q: 'q38',
        t: 't38',
      },
      {
        code: '9.2',
        desc: 'CPA Pessoal Docente (Central)',
        peso: 8.0,
        max: 1,
        unidade: '-',
        q: 'q39',
        t: 't39',
      },
      {
        code: '9.3',
        desc: 'CPA Pessoal Docente (Local)',
        peso: 4.0,
        max: 1,
        unidade: '-',
        q: 'q40',
        t: 't40',
      },
      {
        code: '9.4',
        desc: 'Conselhos ou comitês permanentes externos',
        peso: 1.0,
        max: 1,
        unidade: '-',
        q: 'q41',
        t: 't41',
      },
      {
        code: '9.5',
        desc: 'Colegiado de Cursos',
        peso: 1.0,
        max: 2,
        unidade: 'Curso',
        q: 'q42',
        t: 't42',
      },
      {
        code: '9.6',
        desc: 'Núcleo Docente Estruturante (NDE)',
        peso: 1.0,
        max: 2,
        unidade: 'Curso',
        q: 'q43',
        t: 't43',
      },
      {
        code: '9.7',
        desc: 'Comissão de Processo Administrativo Disciplinar',
        peso: 4.0,
        max: 1,
        unidade: 'Processo',
        q: 'q44',
        t: 't44',
      },
      {
        code: '9.8',
        desc: 'Participação em Direção Sindical (Titular)',
        peso: 4.0,
        max: 1,
        unidade: '-',
        q: 'q45',
        t: 't45',
      },
      {
        code: '9.9',
        desc: 'Fiscalização de contrato',
        peso: 1.0,
        max: 2,
        unidade: 'Contrato',
        q: 'q46',
        t: 't46',
      },
      { isSubtotal: true },
    ],
  },
];
